services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: go-demo:${TAG:-latest}
    container_name: go-demo
    restart: unless-stopped
    ports:
      - "8081:8080"
    networks:
      - api_net

networks:
  api_net:
    driver: bridge 